$base = 'C:\Users\NSB EDITS\Desktop\programing class\MY WORK\donation website\src'
$dirs = @(
  'lib',
  'types',
  'hooks',
  'store',
  'components/layout',
  'components/campaign',
  'components/donation',
  'components/dashboard',
  'components/admin',
  'components/shared',
  'components/auth',
  'app/(auth)/login',
  'app/(auth)/register',
  'app/(auth)/forgot-password',
  'app/(auth)/verify-email',
  'app/(auth)/reset-password',
  'app/(dashboard)',
  'app/(dashboard)/dashboard',
  'app/(dashboard)/dashboard/campaigns',
  'app/(dashboard)/dashboard/donations',
  'app/(dashboard)/dashboard/withdrawals',
  'app/(dashboard)/dashboard/notifications',
  'app/(dashboard)/dashboard/messages',
  'app/(dashboard)/dashboard/settings',
  'app/(main)',
  'app/(main)/campaigns',
  'app/(main)/campaigns/[slug]',
  'app/(main)/categories',
  'app/(main)/categories/[category]',
  'app/(main)/search',
  'app/(main)/about',
  'app/(main)/contact',
  'app/(main)/faq',
  'app/create-campaign',
  'app/admin',
  'app/admin/campaigns',
  'app/admin/users',
  'app/admin/donations',
  'app/admin/withdrawals',
  'app/admin/settings',
  'app/admin/reports',
  'app/api/donations',
  'app/api/campaigns',
  'app/api/webhooks/stripe',
  'app/api/webhooks/paypal',
  'app/api/upload',
  'app/api/auth',
  'emails'
)
foreach ($d in $dirs) {
  $path = Join-Path $base $d
  if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path -Force | Out-Null }
}
Write-Output 'Directories created'
